using System;

namespace D2Packets
{
	public enum GameClientPacket : int
	{
		//Unknown = 0,
		WalkToLocation					= 0x01,
        WalkToTarget                    = 0x02,
		RunToLocation					= 0x03,
        RunToTarget                     = 0x04,
		CastLeftSkill					= 0x05,
		CastLeftSkillOnTarget			= 0x06,
		CastLeftSkillOnTargetStopped	= 0x07,
		RecastLeftSkill					= 0x08,
		RecastLeftSkillOnTarget			= 0x09,
		RecastLeftSkillOnTargetStopped	= 0x0A,
        //0B  	1  	-  	Has something to do with leftskills
		CastRightSkill					= 0x0C,
		CastRightSkillOnTarget			= 0x0D,
		CastRightSkillOnTargetStopped	= 0x0E,
		RecastRightSkill				= 0x0F,
		RecastRightSkillOnTarget		= 0x10,
		RecastRightSkillOnTargetStopped	= 0x11,
		//12  	1  	-  	Has something to do with rightskills
		UnitInteract					= 0x13,
        SendOverheadMessage             = 0x14,
		SendMessage						= 0x15,
		PickItem						= 0x16,
		DropItem						= 0x17,
        DropItemToContainer             = 0x18,
        PickItemFromContainer           = 0x19,
		EquipItem						= 0x1A,
		SwapEquippedItem				= 0x1D,
		UnequipItem						= 0x1C,
		SwapContainerItem				= 0x1F,
		UseInventoryItem				= 0x20,
		StackItems						= 0x21,
		AddBeltItem						= 0x23,
		RemoveBeltItem					= 0x24,
		SwapBeltItem					= 0x25,
		UseBeltItem						= 0x26,
		IdentifyItem					= 0x27,
		EmbedItem   					= 0x29,
		ItemToCube						= 0x2A,
		TownFolkInteract				= 0x2F,
		TownFolkCancelInteraction		= 0x30,
        DisplayQuestMessage             = 0x31, 
		BuyItem							= 0x32,
		SellItem						= 0x33,
		CainIdentifyItems				= 0x34,
		TownFolkRepair					= 0x35,
		HireMercenary					= 0x36,
		IdentifyGambleItem				= 0x37,
        TownFolkMenuSelect              = 0x38,
		//39  	5  	[DWORD UNIT_NPC_ID]  	Buy Health
		IncrementAttribute				= 0x3A,
		IncrementSkill					= 0x3B,
		SelectSkill						= 0x3C,
        HoverUnit                       = 0x3D,
		SendCharacterSpeech				= 0x3F,
		RequestQuestLog					= 0x40,
        Respawn                         = 0x41,
		WaypointInteract				= 0x49,
        RequestReassign                 = 0x4B,
		ClickButton						= 0x4F,
		DropGold						= 0x50,
        SetSkillHotkey                  = 0x51,
        CloseQuest                      = 0x58,
		GoToTownFolk					= 0x59,
		SetPlayerRelation				= 0x5D,
		PartyRequest					= 0x5E,
		UpdatePosition					= 0x5F,
		SwitchWeapons					= 0x60,
		ChangeMercEquipment				= 0x61,
		ResurrectMerc					= 0x62,
		InventoryItemToBelt				= 0x63,
		WardenResponse			    	= 0x66,
		GameLogonRequest				= 0x68,
		ExitGame						= 0x69,
		EnterGame						= 0x6B,
		Ping							= 0x6D,
		
		Invalid							= 0x70,	// Probably 0x6E...
		Wrapper							= 0xF00,

		GoToLocation					= 0xF01,
        GoToTarget                      = 0xF02,
	}
}