Public Interface IGame
    Sub WriteToLog(ByVal Text As String)

#Region " Old "

    'ReadOnly Property CurrentPlayer() As LocalPlayer
    'ReadOnly Property Players() As Collections.Generic.SortedList(Of UInt32, Player)
    'ReadOnly Property NPCs() As Collections.Generic.SortedList(Of UInt32, NPC)
    'ReadOnly Property Monsters() As Collections.Generic.SortedList(Of UInt32, NPC)
    'Item Events
    'Event OnItemDrop(ByVal Item As Item)
    'Event OnRemoveItemFromGround(ByVal ID As UInt32)
    'Event OnWorldItemAction(ByVal ActionType As ItemActionType, ByVal Item As Item)
    'Event OnOwnedItemAction(ByVal ActionType As ItemActionType, ByVal Item As Item)
    'Interaction
    'Sub Interact(ByVal Type As UnitType, ByVal ID As UInt32)
    'Sub UseInventoryItem(ByVal ID As UInt32)
    'Sub UseBeltItem(ByVal ID As UInt32, ByVal ToMerc As Boolean)
    'Sub UseClosestWP(ByVal Destination As WaypointDestination)
    'Sub PickUpItem(ByVal ID As UInt32)
    'Sub SelectSkill(ByVal Skill As SkillType, ByVal LeftSlot As Boolean)
    'Sub SwitchWeapons()
    'Sub UseLeftSkillOnLocation(ByVal x As UInt16, ByVal y As UInt16)
    'Sub UseRightSkillOnLocation(ByVal x As UInt16, ByVal y As UInt16)
    'Sub UseLeftSkillOnObject(ByVal Type As UnitType, ByVal ID As UInt32, ByVal Shift As Boolean)
    'Sub UseRightSkillOnObject(ByVal Type As UnitType, ByVal ID As UInt32, ByVal Shift As Boolean)
    'Sub BuyItem(ByVal ID As UInt32, Optional ByVal Ex As Modifier = Modifier.Standard)
    'Sub SellItem(ByVal ID As UInt32)
    'Sub ItemToBelt(ByVal ID As UInt32, ByVal Location As BeltLocation)
    'Sub RemoveBeltItem(ByVal ID As UInt32)
    'Sub SwitchBeltItem(ByVal CursorID As UInt32, ByVal TargetID As UInt32)
    'Sub ItemToCube(ByVal ID As UInt32, ByVal CubeID As UInt32)
    'Sub ItemToBuffer(ByVal ID As UInt32, ByVal x As UShort, ByVal y As UShort, ByVal Type As BufferType)
    'Sub DropItem(ByVal ID As UInt32)
    'Sub MercItemToCursor(ByVal Location As MercEquipLocation)
    'Sub CursorItemToMerc()
    'Sub RequestObjectUpdate(ByVal Type As UnitType, ByVal ID As UInt32)
    'Sub AskToResMerc()
    'Sub AskToRepairAll()
    'Sub AskToIdentifyAll()
    'Sub TPScrollToBook(ByVal ScrollID As UInt32)
    'Sub DropGold(ByVal Amount As Integer)
    'Death
    'Event OnSlain(ByVal PlayerName As String)
    'Event OnSlainByPlayer(ByVal PlayerName As String, ByVal SlainByName As String, ByVal SlainByClass As CharacterClass)
    'Event OnSlainByMonster(ByVal PlayerName As String, ByVal Monster As NPCType)
    'Event OnSlainByObject(ByVal PlayerName As String, ByVal ObjectID As GameObjectID)
    'Party Changes
    'Event OnPartyChange(ByVal PlayerID As UInt32, ByVal Relationship As PartyRelationshipType)
    'Player Join/Leave Events
    'Event OnPlayerJoin(ByVal PlayerID As UInt32, ByVal PlayerClass As CharacterClass, ByVal PlayerName As String, ByVal PlayerLevel As UInt16, ByVal PartyID As UInt16)
    'Event OnPlayerLeave(ByVal PlayerClass As CharacterClass, ByVal PlayerName As String, ByVal PlayerLevel As UInt16, ByVal PartyID As UInt16, ByVal Reason As String)
    'Sub [Exit]()
    'Event OnGameStart()
    'NPCs
    'Event OnAssignNPC(ByVal ID As UInt32, ByVal Type As NPCType, ByVal Life As Integer, ByVal x As UInt16, ByVal y As UInt16)
    'Event OnNPCMove(ByVal ID As UInt32, ByVal x As UInt16, ByVal y As UInt16)
    'Event OnNPCMoveToObject(ByVal ID As UInt32, ByVal MovementType As Byte, ByVal currentX As UInt16, ByVal currentY As UInt16, ByVal targetType As UnitType, ByVal targetID As UInt32)
    'Event OnMonsterAttacking(ByVal MonsterID As UInt32, ByVal AttackType As UInt16, ByVal Target As UInt32, ByVal TargetType As UnitType, ByVal x As UInt16, ByVal y As UInt16)
    'Event OnMonsterDeath(ByVal MonsterID As UInt32)
    'World
    'Event OnAssignWorldObject(ByVal UnitID As UInt32, ByVal ObjectID As GameObjectID, ByVal x As UInt16, ByVal y As UInt16, ByVal ObjectState As GameObjectState, ByVal InteractionType As GameInteractiveObjectType, ByVal Destination As AreaLevel)
    'Event OnAssignWarp(ByVal Type As UnitType, ByVal ID As UInt32, ByVal Warp As WarpType, ByVal x As UInt16, ByVal y As UInt16)
    'Reassign Event
    'Event OnReassign(ByVal Type As UnitType, ByVal ID As UInt32, ByVal x As UInt16, ByVal y As UInt16, ByVal Reassign As Boolean)
    'Player Stat Change
    'Event OnLifeManaChange(ByVal x As UInt16, ByVal y As UInt16, ByVal Stamina As UInt16, ByVal Life As UInt16, ByVal Mana As UInt16)
    'Run/Walk Methods
    'Event OnMove(ByVal x As UInt16, ByVal y As UInt16, ByVal Walk As Boolean)
    'Sub Move(ByVal x As UInt16, ByVal y As UInt16, Optional ByVal Walk As Boolean = False)
    'Sub Move(ByVal Type As UnitType, ByVal ID As UInt32, Optional ByVal walk As Boolean = False)
    'Event OnMoved(ByVal x As UInt16, ByVal y As UInt16, ByVal Stamina As UInt16)
    'Event OnAreaChange(ByVal OldArea As AreaLevel, ByVal NewArea As AreaLevel)
    'Event OnActChange(ByVal OldAct As Act, ByVal NewAct As Act)
    'Corpse Pickup
    'Event OnVisibleCorpse(ByVal PlayerID As UInteger, ByVal CorpseID As UInteger)
    'Event OnCorpsePickup()
    'Useful Methods
    'Sub TalkToNPC(ByVal NPC As TownFolk)
    'Sub CancelNPC()
    'Function InTown() As Boolean
    'Sub GoToTown()
    'Sub GoToStash()
    'Sub TPToTown()
    'Sub TalkToRepairNPC()
    'Sub TalkToMercNPC()
    'Sub TalkToHealNPC()
    'Sub TalkToDeckardCain()
    'Sub ResMerc()
    'Sub RepairAll()
    'Sub IdentifyAll()
    'Sub PickupCorpse()
    'Chat Methods
    'Event OnReceiveMessage(ByVal Packet As GameServer.GameMessage)
    'Event OnSendMessage(ByVal Packet As GameClient.SendMessage)
    Sub SendMessage(ByVal Message As String)
    Sub ReceiveMessage(ByVal Name As String, ByVal Message As String)


#End Region

#Region " Game Client Events "

    Event OnAddBeltItem(ByVal Packet As GameClient.AddBeltItem)
    Event OnBuyItem(ByVal Packet As GameClient.BuyItem)
    Event OnCainIdentifyItems(ByVal Packet As GameClient.CainIdentifyItems)
    Event OnCastLeftSkill(ByVal Packet As GameClient.CastLeftSkill)
    Event OnCastLeftSkillOnTarget(ByVal Packet As GameClient.CastLeftSkillOnTarget)
    Event OnCastLeftSkillOnTargetStopped(ByVal Packet As GameClient.CastLeftSkillOnTargetStopped)
    Event OnCastRightSkill(ByVal Packet As GameClient.CastRightSkill)
    Event OnCastRightSkillOnTarget(ByVal Packet As GameClient.CastRightSkillOnTarget)
    Event OnCastRightSkillOnTargetStopped(ByVal Packet As GameClient.CastRightSkillOnTargetStopped)
    Event OnChangeMercEquipment(ByVal Packet As GameClient.ChangeMercEquipment)
    Event OnClickButton(ByVal Packet As GameClient.ClickButton)
    Event OnCloseQuest(ByVal Packet As GameClient.CloseQuest)
    Event OnDisplayQuestMessage(ByVal Packet As GameClient.DisplayQuestMessage)
    Event OnDropGold(ByVal Packet As GameClient.DropGold)
    Event OnDropItem(ByVal Packet As GameClient.DropItem)
    Event OnDropItemToContainer(ByVal Packet As GameClient.DropItemToContainer)
    Event OnEmbedItem(ByVal Packet As GameClient.EmbedItem)
    Event OnEnterGame(ByVal Packet As GameClient.EnterGame)
    Event OnEquipItem(ByVal Packet As GameClient.EquipItem)
    Event OnExitGame(ByVal Packet As GameClient.ExitGame)
    Event OnGameLogonRequest(ByVal Packet As GameClient.GameLogonRequest)
    Event OnGoToLocation(ByVal Packet As GameClient.GoToLocation)
    Event OnGoToTarget(ByVal Packet As GameClient.GoToTarget)
    Event OnGoToTownFolk(ByVal Packet As GameClient.GoToTownFolk)
    Event OnHireMercenary(ByVal Packet As GameClient.HireMercenary)
    Event OnHoverUnit(ByVal Packet As GameClient.HoverUnit)
    Event OnIdentifyGambleItem(ByVal Packet As GameClient.IdentifyGambleItem)
    Event OnIdentifyItem(ByVal Packet As GameClient.IdentifyItem)
    Event OnIncrementAttribute(ByVal Packet As GameClient.IncrementAttribute)
    Event OnIncrementSkill(ByVal Packet As GameClient.IncrementSkill)
    Event OnInventoryItemToBelt(ByVal Packet As GameClient.InventoryItemToBelt)
    Event OnItemToCube(ByVal Packet As GameClient.ItemToCube)
    Event OnPartyRequest(ByVal Packet As GameClient.PartyRequest)
    Event OnPickItem(ByVal Packet As GameClient.PickItem)
    Event OnPickItemFromContainer(ByVal Packet As GameClient.PickItemFromContainer)
    Event OnPing(ByVal Packet As GameClient.Ping)
    Event OnRecastLeftSkill(ByVal Packet As GameClient.RecastLeftSkill)
    Event OnRecastLeftSkillOnTarget(ByVal Packet As GameClient.RecastLeftSkillOnTarget)
    Event OnRecastLeftSkillOnTargetStopped(ByVal Packet As GameClient.RecastLeftSkillOnTargetStopped)
    Event OnRecastRightSkill(ByVal Packet As GameClient.RecastRightSkill)
    Event OnRecastRightSkillOnTarget(ByVal Packet As GameClient.RecastRightSkillOnTarget)
    Event OnRecastRightSkillOnTargetStopped(ByVal Packet As GameClient.RecastRightSkillOnTargetStopped)
    Event OnRemoveBeltItem(ByVal Packet As GameClient.RemoveBeltItem)
    Event OnRequestQuestLog(ByVal Packet As GameClient.RequestQuestLog)
    Event OnRequestReassign(ByVal Packet As GameClient.RequestReassign)
    Event OnRespawn(ByVal Packet As GameClient.Respawn)
    Event OnResurrectMerc(ByVal Packet As GameClient.ResurrectMerc)
    Event OnRunToLocation(ByVal Packet As GameClient.RunToLocation)
    Event OnRunToTarget(ByVal Packet As GameClient.RunToTarget)
    Event OnSelectSkill(ByVal Packet As GameClient.SelectSkill)
    Event OnSellItem(ByVal Packet As GameClient.SellItem)
    Event OnSendCharacterSpeech(ByVal Packet As GameClient.SendCharacterSpeech)
    Event OnSendMessage(ByVal Packet As GameClient.SendMessage)
    Event OnSendOverheadMessage(ByVal Packet As GameClient.SendOverheadMessage)
    Event OnSetPlayerRelation(ByVal Packet As GameClient.SetPlayerRelation)
    Event OnSetSkillHotkey(ByVal Packet As GameClient.SetSkillHotkey)
    Event OnStackItems(ByVal Packet As GameClient.StackItems)
    Event OnSwapBeltItem(ByVal Packet As GameClient.SwapBeltItem)
    Event OnSwapContainerItem(ByVal Packet As GameClient.SwapContainerItem)
    Event OnSwapEquippedItem(ByVal Packet As GameClient.SwapEquippedItem)
    Event OnSwitchWeapons(ByVal Packet As GameClient.SwitchWeapons)
    Event OnTownFolkCancelInteraction(ByVal Packet As GameClient.TownFolkCancelInteraction)
    Event OnTownFolkInteract(ByVal Packet As GameClient.TownFolkInteract)
    Event OnTownFolkMenuSelect(ByVal Packet As GameClient.TownFolkMenuSelect)
    Event OnTownFolkRepair(ByVal Packet As GameClient.TownFolkRepair)
    Event OnUnequipItem(ByVal Packet As GameClient.UnequipItem)
    Event OnUnitInteract(ByVal Packet As GameClient.UnitInteract)
    Event OnUpdatePosition(ByVal Packet As GameClient.UpdatePosition)
    Event OnUseBeltItem(ByVal Packet As GameClient.UseBeltItem)
    Event OnUseInventoryItem(ByVal Packet As GameClient.UseInventoryItem)
    Event OnWalkToLocation(ByVal Packet As GameClient.WalkToLocation)
    Event OnWalkToTarget(ByVal Packet As GameClient.WalkToTarget)
    Event OnWardenResponse(ByVal Packet As GameClient.WardenResponse)
    Event OnWaypointInteract(ByVal Packet As GameClient.WaypointInteract)

#End Region

#Region " Game Server Events "

    Event OnAboutPlayer(ByVal Packet As GameServer.AboutPlayer)
    Event OnAcceptTrade(ByVal Packet As GameServer.AcceptTrade)
    Event OnAddUnit(ByVal Packet As GameServer.AddUnit)
    Event OnAssignGameObject(ByVal Packet As GameServer.AssignGameObject)
    Event OnAssignMerc(ByVal Packet As GameServer.AssignMerc)
    Event OnAssignNPC(ByVal Packet As GameServer.AssignNPC)
    Event OnAssignPlayer(ByVal Packet As GameServer.AssignPlayer)
    Event OnAssignPlayerCorpse(ByVal Packet As GameServer.AssignPlayerCorpse)
    Event OnAssignPlayerToParty(ByVal Packet As GameServer.AssignPlayerToParty)
    Event OnAssignSkill(ByVal Packet As GameServer.AssignSkill)
    Event OnAssignSkillHotkey(ByVal Packet As GameServer.AssignSkillHotkey)
    Event OnAssignWarp(ByVal Packet As GameServer.AssignWarp)
    Event OnAttributeNotification(ByVal Packet As GameServer.AttributeNotification)
    Event OnDelayedState(ByVal Packet As GameServer.DelayedState)
    Event OnEndState(ByVal Packet As GameServer.EndState)
    Event OnGainExperience(ByVal Packet As GameServer.GainExperience)
    Event OnGameHandshake(ByVal Packet As GameServer.GameHandshake)
    Event OnGameLoading(ByVal Packet As GameServer.GameLoading)
    Event OnGameLogonReceipt(ByVal Packet As GameServer.GameLogonReceipt)
    Event OnGameLogonSuccess(ByVal Packet As GameServer.GameLogonSuccess)
    Event OnGameLogoutSuccess(ByVal Packet As GameServer.GameLogoutSuccess)
    Event OnReceiveMessage(ByVal Packet As GameServer.GameMessage)
    Event OnGameOver(ByVal Packet As GameServer.GameOver)
    Event OnGoldTrade(ByVal Packet As GameServer.GoldTrade)
    Event OnInformationMessage(ByVal Packet As GameServer.InformationMessage)
    '****************
    Event OnOwnedItemAction(ByVal Packet As GameServer.OwnedItemAction)
    '****************
    Event OnItemAction(ByVal Packet As GameServer.ItemAction)

    Event OnItemTriggerSkill(ByVal Packet As GameServer.ItemTriggerSkill)
    Event OnLoadAct(ByVal Packet As GameServer.LoadAct)
    Event OnLoadDone(ByVal Packet As GameServer.LoadDone)
    Event OnMapAdd(ByVal Packet As GameServer.MapAdd)
    Event OnMapRemove(ByVal Packet As GameServer.MapRemove)
    Event OnMercAttributeNotification(ByVal Packet As GameServer.MercAttributeNotification)
    Event OnMercForHire(ByVal Packet As GameServer.MercForHire)
    Event OnMercForHireListStart(ByVal Packet As GameServer.MercForHireListStart)
    Event OnMercGainExperience(ByVal Packet As GameServer.MercGainExperience)
    Event OnMonsterAttack(ByVal Packet As GameServer.MonsterAttack)
    Event OnNPCAction(ByVal Packet As GameServer.NPCAction)
    Event OnNPCGetHit(ByVal Packet As GameServer.NPCGetHit)
    Event OnNPCHeal(ByVal Packet As GameServer.NPCHeal)
    Event OnNPCInfo(ByVal Packet As GameServer.NPCInfo)
    Event OnNPCMove(ByVal Packet As GameServer.NPCMove)
    Event OnNPCMoveToTarget(ByVal Packet As GameServer.NPCMoveToTarget)
    Event OnNPCStop(ByVal Packet As GameServer.NPCStop)
    Event OnNPCWantsInteract(ByVal Packet As GameServer.NPCWantsInteract)
    Event OnOpenWaypoint(ByVal Packet As GameServer.OpenWaypoint)
    Event OnPartyMemberPulse(ByVal Packet As GameServer.PartyMemberPulse)
    Event OnPartyMemberUpdate(ByVal Packet As GameServer.PartyMemberUpdate)
    Event OnPartyRefresh(ByVal Packet As GameServer.PartyRefresh)
    Event OnPlayerAttributeNotification(ByVal Packet As GameServer.PlayerAttributeNotification)
    Event OnPlayerClearCursor(ByVal Packet As GameServer.PlayerClearCursor)
    Event OnPlayerCorpseVisible(ByVal Packet As GameServer.PlayerCorpseVisible)
    Event OnPlayerInGame(ByVal Packet As GameServer.PlayerInGame)
    Event OnPlayerInSight(ByVal Packet As GameServer.PlayerInSight)
    Event OnPlayerKillCount(ByVal Packet As GameServer.PlayerKillCount)
    Event OnPlayerLeaveGame(ByVal Packet As GameServer.PlayerLeaveGame)
    Event OnPlayerLifeManaChange(ByVal Packet As GameServer.PlayerLifeManaChange)
    Event OnPlayerMove(ByVal Packet As GameServer.PlayerMove)
    Event OnPlayerMoveToTarget(ByVal Packet As GameServer.PlayerMoveToTarget)
    Event OnPlayerPartyRelationship(ByVal Packet As GameServer.PlayerPartyRelationship)
    Event OnPlayerReassign(ByVal Packet As GameServer.PlayerReassign)
    Event OnPlayerRelationship(ByVal Packet As GameServer.PlayerRelationship)
    Event OnPlayerStop(ByVal Packet As GameServer.PlayerStop)
    Event OnPlaySound(ByVal Packet As GameServer.PlaySound)
    Event OnPong(ByVal Packet As GameServer.Pong)
    Event OnPortalInfo(ByVal Packet As GameServer.PortalInfo)
    Event OnPortalOwnership(ByVal Packet As GameServer.PortalOwnership)
    Event OnQuestItemState(ByVal Packet As GameServer.QuestItemState)
    Event OnRelator1(ByVal Packet As GameServer.Relator1)
    Event OnRelator2(ByVal Packet As GameServer.Relator2)
    Event OnRemoveGroundUnit(ByVal Packet As GameServer.RemoveGroundUnit)
    Event OnReportKill(ByVal Packet As GameServer.ReportKill)
    Event OnRequestLogonInfo(ByVal Packet As GameServer.RequestLogonInfo)
    Event OnSetGameObjectMode(ByVal Packet As GameServer.SetGameObjectMode)
    Event OnSetItemState(ByVal Packet As GameServer.SetItemState)
    Event OnSetNPCMode(ByVal Packet As GameServer.SetNPCMode)
    Event OnSetState(ByVal Packet As GameServer.SetState)
    Event OnSkillsLog(ByVal Packet As GameServer.SkillsLog)
    Event OnSmallGoldAdd(ByVal Packet As GameServer.SmallGoldAdd)
    Event OnSummonAction(ByVal Packet As GameServer.SummonAction)
    Event OnSwitchWeaponSet(ByVal Packet As GameServer.SwitchWeaponSet)
    Event OnTransactionComplete(ByVal Packet As GameServer.TransactionComplete)
    Event OnUnitUseSkill(ByVal Packet As GameServer.UnitUseSkill)
    Event OnUnitUseSkillOnTarget(ByVal Packet As GameServer.UnitUseSkillOnTarget)
    Event OnUnloadDone(ByVal Packet As GameServer.UnloadDone)
    Event OnUpdateGameQuestLog(ByVal Packet As GameServer.UpdateGameQuestLog)
    Event OnUpdateItemStats(ByVal Packet As GameServer.UpdateItemStats)
    Event OnUpdateItemUI(ByVal Packet As GameServer.UpdateItemUI)
    Event OnUpdatePlayerItemSkill(ByVal Packet As GameServer.UpdatePlayerItemSkill)
    Event OnUpdateQuestInfo(ByVal Packet As GameServer.UpdateQuestInfo)
    Event OnUpdateQuestLog(ByVal Packet As GameServer.UpdateQuestLog)
    Event OnUpdateSkill(ByVal Packet As GameServer.UpdateSkill)
    Event OnUseSpecialItem(ByVal Packet As GameServer.UseSpecialItem)
    Event OnUseStackableItem(ByVal Packet As GameServer.UseStackableItem)
    Event OnWalkVerify(ByVal Packet As GameServer.WalkVerify)
    Event OnWardenCheck(ByVal Packet As GameServer.WardenCheck)

#End Region

#Region " Packet Methods "

    Sub ReceivePacket(ByRef bytes() As Byte)
    Sub ReceivePacket(ByRef bytes() As Byte, ByVal length As Integer)
    Sub ReceivePacket(ByVal Packet As D2Packets.D2Packet)
    Sub SendPacket(ByRef bytes() As Byte)
    Sub SendPacket(ByRef bytes() As Byte, ByVal length As Integer)
    Sub SendPacket(ByVal Packet As D2Packets.D2Packet)
    Event OnReceivePacket(ByRef Packet As Packet)
    Event OnSendPacket(ByRef Packet As Packet)

#End Region

    'Hot Keys
    'Sub RegisterHotKey(ByVal Key As System.Windows.Forms.Keys, ByVal Modifiers As HotKey.HotKeyModifiers)
    'Event OnHotKey(ByVal Key As System.Windows.Forms.Keys, ByVal Modifiers As HotKey.HotKeyModifiers)
End Interface