Namespace GameClient

    Public Enum GameClientPacket
        WalkToLocation = 1
        WalkToTarget = 2
        RunToLocation = 3
        RunToTarget = 4
        CastLeftSkill = 5
        CastLeftSkillOnTarget = 6
        CastLeftSkillOnTargetStopped = 7
        RecastLeftSkill = 8
        RecastLeftSkillOnTarget = 9
        RecastLeftSkillOnTargetStopped = 10
        CastRightSkill = 12
        CastRightSkillOnTarget = 13
        CastRightSkillOnTargetStopped = 14
        RecastRightSkill = 15
        RecastRightSkillOnTarget = 16
        RecastRightSkillOnTargetStopped = 17
        UnitInteract = 19
        SendOverheadMessage = 20
        SendMessage = 21
        PickItem = 22
        DropItem = 23
        DropItemToContainer = 24
        PickItemFromContainer = 25
        EquipItem = 26
        UnequipItem = 28
        SwapEquippedItem = 29
        SwapContainerItem = 31
        UseInventoryItem = 32
        StackItems = 33
        AddBeltItem = 35
        RemoveBeltItem = 36
        SwapBeltItem = 37
        UseBeltItem = 38
        IdentifyItem = 39
        EmbedItem = 41
        ItemToCube = 42
        TownFolkInteract = 47
        TownFolkCancelInteraction = 48
        DisplayQuestMessage = 49
        BuyItem = 50
        SellItem = 51
        CainIdentifyItems = 52
        TownFolkRepair = 53
        HireMercenary = 54
        IdentifyGambleItem = 55
        TownFolkMenuSelect = 56
        IncrementAttribute = 58
        IncrementSkill = 59
        SelectSkill = 60
        HoverUnit = 61
        SendCharacterSpeech = 63
        RequestQuestLog = 64
        Respawn = 65
        WaypointInteract = 73
        RequestReassign = 75
        ClickButton = 79
        DropGold = 80
        SetSkillHotkey = 81
        CloseQuest = 88
        GoToTownFolk = 89
        SetPlayerRelation = 93
        PartyRequest = 94
        UpdatePosition = 95
        SwitchWeapons = 96
        ChangeMercEquipment = 97
        ResurrectMerc = 98
        InventoryItemToBelt = 99
        WardenResponse = 102
        GameLogonRequest = 104
        ExitGame = 105
        EnterGame = 107
        Ping = 109

        Invalid = 110

        Wrapper = 3840
        GoToLocation = 3841
        GoToTarget = 3842
    End Enum

End Namespace